AWSTemplateFormatVersion: '2010-09-09'
Description: Create CloudWatch Alarms for EC2 CPU and RAM Utilization
Parameters:
  EC2InstanceId:
    Description: ID of the EC2 instance to monitor
    Type: String
  CPUMetricThreshold:
    Description: CPU utilization threshold for the alarm
    Type: Number
    Default: 70
    MinValue: 1
    MaxValue: 100
    ConstraintDescription: Threshold value must be between 1 and 100
  RAMMetricThreshold:
    Description: RAM utilization threshold for the alarm (percentage)
    Type: Number
    Default: 70
    MinValue: 1
    MaxValue: 100
    ConstraintDescription: Threshold value must be between 1 and 100

Resources:
  CPUMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm for EC2 CPU Utilization"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "InstanceId"
          Value: !Ref EC2InstanceId
      Statistic: "Average"
      Period: 300 # 5 minutes
      EvaluationPeriods: 1
      Threshold: !Ref CPUMetricThreshold
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref SNSNotificationTopic # Replace with your SNS topic ARN
      TreatMissingData: notBreaching

  RAMMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm for EC2 RAM Utilization"
      Namespace: "System/Linux" # Adjust the namespace based on your instance's OS
      MetricName: "MemoryUtilization" # Metric name may vary depending on OS
      Dimensions:
        - Name: "InstanceId"
          Value: !Ref EC2InstanceId
      Statistic: "Average"
      Period: 300 # 5 minutes
      EvaluationPeriods: 1
      Threshold: !Ref RAMMetricThreshold
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref SNSNotificationTopic # Replace with your SNS topic ARN
      TreatMissingData: notBreaching

Outputs:
  CPUMetricAlarmName:
    Description: Name of the CloudWatch Alarm for CPU Utilization
    Value: !Ref CPUMetricAlarm

  RAMMetricAlarmName:
    Description: Name of the CloudWatch Alarm for RAM Utilization
    Value: !Ref RAMMetricAlarm
