AWSTemplateFormatVersion: 2010-09-09
Description: >
  This Couldformation template creates SNS Topic given paramaters.
  An appropirate protocal should be chosen for the subscription to the SNS topic.

# Author: Yann Mulonda - yann.mulonda@icf.com - ICF SCS
#------------------------------------------------------------------------------------*
# SNS is a Simple Notification Service. It's used by Cloudwatch to send alert emails. 
# An SNS topic needs to be created and then an endpoint needs to be subscribed to it.

# The SNS topic created are what will be refered to on a CloudWatch alarms:
# refer to: create_ecs_cloudwatch_alarm.yml cloudformation template
#______
# more details about SNS Topic properties can be found here:
# https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sns/blob/master/aws-sns-topic/docs/README.md

# define paremeter
Parameters:
  Parameters:
  SNSTopicName:
    Type: String
    Description: Name for the SNS topic
  SNSTopicDisplayName:
    Type: String
    Description: Display name for the SNS topic
  SubscriptionEndPoint:
    Type: String
    Description: The endpoint that receives notifications.
  SubscriptionProtocol:
    Type: String
    Description: The subscription protocol
    AllowedValues:
    - http
    - https
    - email
    - email-json
    - sms
    - sqs
    - application
    - lambda
    Default: email
Mappings: {}
Conditions: {}

# Create AWS resources
Resources:
  # None of the SNSTopic properties are requied to be added on the resources definition
  # review snsReadMe for more details
  SNSTopic:
    Type: AWS::SNS::Topic
    # Properties: {}
    Properties:
      DisplayName: !Ref SNSTopicDisplayName
      TopicName: !Ref SNSTopicName

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SubscriptionEndPoint
      Protocol: !Ref SubscriptionProtocol
      TopicArn: !Ref SNSTopic

# ouptut is optional
Outputs:
  QueueName:
    Description: Name of the SNS Topic we created
    Value:
      Fn::GetAtt:
      - SNSTopic
      - TopicName
  TopicARN:
    Description: ARN of the SNS Topic we created 
    Value: !Ref SNSTopic