# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # CloudFormation Linter enables arbitrary actions for interacting with CloudFormation Linter 
  # to validate CloudFormation yaml/json templates against the CloudFormation spec and additional checks. 
  # Includes checking valid values for resource properties and best practices.
  validate-templates:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Validate AWS SNS CouldFormation templates
        run: |
          cfn-lint --version
          cfn-lint -t ./aws-sns/create_sns_topic.yml
          cfn-lint -t ./aws-sns/create_sns_subscriber.yml
          cfn-lint -t ./aws-sns/create_sns_topic_subscriber.yml

      - name: Validate CouldWatch Alarm CouldFormation templates.
        run: |
          cfn-lint --version
          cfn-lint -t ./aws-cloudwatch-alarms/create_ecs_cloudwatch_alarm.yml
          cfn-lint -t ./aws-cloudwatch-alarms/create_ec2_cloudwatch_alarm.yml

      - name: Validate CouldWatch Dashboards CouldFormation templates.
        run: |
          cfn-lint --version
          cfn-lint -t ./aws-cloudwatch-dashboards/create_dashboard_v1.yml
          cfn-lint -t ./aws-cloudwatch-dashboards/create_service_dashboard.yml
          cfn-lint -t ./aws-cloudwatch-dashboards/create_dashboard_cloudwatch.
          
  # A test "build" action
  build:
    runs-on: ubuntu-latest
  
    # only if the app build and test successfully
    needs: [validate-templates]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: show the job trigger
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: show the OS of the Github Actions runner
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: show branch and repo name
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: show step after repo checkout
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: display a message
        run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
